#!/usr/bin/env python3
"""Emit a C stub for every exported symbol that is not implemented yet.

The point is that the shared library exports its complete symbol set from the
first buildable commit. A client can then link and load against it immediately,
and every later step is "move a name from symbols.txt to implemented.txt and
watch a conformance failure disappear" rather than "hope the link works at the
end".

Stubs are written in C rather than Swift on purpose. A C stub is the header's
own declaration with a body attached, so no signature is retyped and no C-to-
Swift type mapping can go wrong. That is exactly the class of mistake that would
otherwise show up as memory corruption in the caller.

A stub returns the failure value the API documents for that function — NULL for
a handle or pointer, -1 for an int, 0 for a size. It never returns something a
caller could mistake for success.

Forgetting to add a name to implemented.txt is a duplicate symbol at link time,
and forgetting to remove one is a missing symbol, so the two files cannot
silently drift apart.

    usage: gen-stubs.py [--check]

    --check  exit non-zero if the generated file is out of date, for CI
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
HEADER = ROOT / "Sources" / "CTurboJPEG" / "include" / "turbojpeg.h"
SYMBOLS = ROOT / "scripts" / "symbols.txt"
IMPLEMENTED = ROOT / "scripts" / "implemented.txt"
OUTPUT = ROOT / "Sources" / "CTurboJPEG" / "gen" / "stubs.c"

PREAMBLE = """/* stubs.c - generated by scripts/gen-stubs.py; do not edit
 *
 * Definitions for the published symbols this library does not implement yet.
 * They exist so the export table is complete and a client links and loads
 * against us unchanged. Each one fails through the API's own error convention
 * rather than returning a plausible wrong answer.
 *
 * Retire a stub by adding its name to scripts/implemented.txt and regenerating.
 */

#include "turbojpeg.h"

"""


def read_list(path: pathlib.Path) -> list[str]:
    return [
        line.strip()
        for line in path.read_text().splitlines()
        if line.strip() and not line.strip().startswith(("#", "["))
    ]


def declarations(source: str) -> dict[str, str]:
    """Maps each exported name to its declaration text, parameters included."""
    # Drop comments so a prototype quoted in documentation is not mistaken for a
    # real one, and collapse whitespace so a declaration split over lines
    # becomes one line.
    source = re.sub(r"/\*.*?\*/", " ", source, flags=re.S)

    found: dict[str, str] = {}
    # Both spellings matter: the modern API is tj*, but the 1.x entry points
    # TJBUFSIZE and TJBUFSIZEYUV are upper case and still exported.
    for match in re.finditer(r"DLLEXPORT\s+([^;{]*?\b((?:tj|TJ)[A-Za-z0-9_]*)\s*\([^;{]*?\))\s*;",
                             source, re.S):
        declaration = " ".join(match.group(1).split())
        name = match.group(2)
        # The first declaration wins. tj3Init appears twice — once for real and
        # once inside the __DOXYGEN__ branch — and either spelling is fine
        # because it is implemented in Swift and never stubbed.
        found.setdefault(name, declaration)
    return found


def failure(declaration: str, name: str) -> str:
    """The return statement for a function that did not run."""
    prefix = declaration.split(name)[0].strip()

    if prefix == "void":
        return ""
    if "*" in prefix or prefix.endswith("tjhandle"):
        return "  return NULL;"
    if "size_t" in prefix or "unsigned" in prefix:
        return "  return 0;"
    return "  return -1;"


def render() -> tuple[str, int, int]:
    exported = read_list(SYMBOLS)
    implemented = set(read_list(IMPLEMENTED))
    declared = declarations(HEADER.read_text())

    unknown = implemented - set(exported)
    if unknown:
        sys.exit(
            "implemented.txt lists names that are not exported: "
            + ", ".join(sorted(unknown))
        )

    undeclared = [name for name in exported if name not in declared]
    if undeclared:
        sys.exit(
            "exported symbols missing a declaration in turbojpeg.h: "
            + ", ".join(sorted(undeclared))
        )

    parts = [PREAMBLE]
    stubbed = 0
    for name in exported:
        if name in implemented:
            continue
        stubbed += 1
        body = failure(declared[name], name)
        parts.append(f"{declared[name]}\n{{\n")
        if body:
            parts.append(body + "\n")
        parts.append("}\n\n")

    return "".join(parts), stubbed, len(exported)


def main() -> None:
    text, stubbed, total = render()

    if "--check" in sys.argv:
        current = OUTPUT.read_text() if OUTPUT.exists() else ""
        if current != text:
            sys.exit(f"{OUTPUT.relative_to(ROOT)} is out of date; run scripts/gen-stubs.py")
        print(f"{OUTPUT.relative_to(ROOT)} is up to date")
        return

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(text)
    print(
        f"wrote {stubbed} stubs to {OUTPUT.relative_to(ROOT)} "
        f"({total - stubbed}/{total} implemented)"
    )


if __name__ == "__main__":
    main()
